### ISSUE TITLE
Audit OC 957

### ISSUE THREAD

**Issue by hegdesonia** [HopkinsIDD/cholera-database#467]
This UID needs to be deleted. Was added to UID 958 (#191) as they had the same source file.

**Comment by eclee25** [comment]
The changes to this UID had only been made on the staging server. I removed the tag for deletion because I think it's okay to have separate OCs for the multiple reports in a single ProMed email. This OC only reflects data in "[3] Cholera - Nigeria (Gombe)" in the source document.

Added case definitions and Primary flag.
