### ISSUE TITLE
Audit OC 956

### ISSUE THREAD

**Issue by hegdesonia** [HopkinsIDD/cholera-database#468]
This UID needs to be deleted. Data was added to UID 958 (#191) as they had the same source file.

**Comment by eclee25** [comment]
The above described changes were only added to the staging server. I removed the label for deletion because the data in OCs 958, 957, and 956 were from different ProMed reports (within the same ProMed update) and it's okay to keep them separate. 

Added primary flag, pdf of source documents, source notes, and case defs
